Fix AttributeError in reference to pymongo.uri_parser.
